# Generated by Django 4.2.8 on 2023-12-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.IntegerField(choices=[(7, 'SEO'), (6, 'Team Lead'), (5, 'Tech Lead'), (4, 'Senior'), (3, 'Middle'), (2, 'Junior'), (1, 'Trainee')])),
                ('joined', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='logic.employeemodel')),
            ],
        ),
    ]
